### ISSUE TITLE
The Vaccination Coverage graph does not follow the theme

### ISSUE THREAD

**Issue by humble-barnacle001** [incovid19/incovid19-react#1]
**Describe the bug**
The graph in Vaccination Coverage (States) and Vaccination Coverage (Districts) section remains in light mode even in dark mode theme

**To Reproduce**

1. Go to 'homepage'
2. Scroll down to 'Vaccination Coverage (States)'
3.  See that graph is in light theme even in dark mode

**Expected behavior**
The graph should be in dark theme in dark mode of the webpage.

**Smartphone (please complete the following information):**

- OS: Android
- Browser: Chrome
- Version: 96

**Comment by aksanoble** [comment]
Thank you for pointing this out. Fixed in https://github.com/incovid19/incovid19-react/commit/331a598d7d50524b916efaf5b61a3480d910702c
