### ISSUE TITLE
Case growth column shows ∞% for all states (and cities)

### ISSUE THREAD

**Issue by pinaki-das-sage** [incovid19/incovid19-react#5]
**Describe the bug**
The case growth column shows ∞%

**To Reproduce**

1. Go to 'homepage'
2. Expand the table of data to show all columns
3. check under the case growth column (it shows ∞%)

**Expected behavior**
Show the case growth percentage from last week compared to week a fortnight ago

**Desktop**
- OS: Windows 10
- Browser - Chrome
- Version - 96.0.4664.110 (Official Build) (64-bit)

**Comment by pinaki-das-sage** [comment]
seems the delta21_14 values are missing, this is a problem with the data scraper and not with the UI

**Comment by aksanoble** [comment]
Thank you for reporting this. This is now fixed.
