### ISSUE TITLE
Telengana testing and district-wise data is available

### ISSUE THREAD

**Issue by DhruvM7** [incovid19/incovid19-react#6]
Hi, thanks for reviving and maintaining this project!

The [Telangana](https://www.incovid19.org/state/TG) page doesn't have testing (and hence positivity rate) data, nor district-wise breakdown, and says district wise breakdown is not available in the state bulletin.

However the daily PDFs released at https://covid19.telangana.gov.in/announcements/media-bulletins/ have testing data on the 1st page, and last 7 days district wise cases breakdown on 2nd page.

Please consider parsing these values from the bulletin.

**Comment by aksanoble** [comment]
Thank you for sharing the resource. We'll evaluate the data source and incorporate.

**Comment by aksanoble** [comment]
It turns out complete data i.e. recovered, deceased data isn't available at the district level. Only daily new cases are published. Hence we can't incorporate at this point in time.

**Comment by DhruvM7** [comment]
Okay, what about taking state-wide testing data from the resource. Currently the page doesn't have state-wide tests done and hence no positivity rate also.
